from .magnitude.distances import *
from .magnitude.compute import *
from .magnitude.weights import *
from .magnitude.scales import *
from .magnitude.convergence import *
from .magnitude.dimension import *
from .magnitude.function_operations import *
from .utils.plots import *
from .utils.datasets import *
from .magnipy import Magnipy
from .diversipy import Diversipy
from .utils.tutorial_data import *
